export const movies = [
    {
      name: "Debugging Dreams",
      description: "A heartwarming and comedic movie that follows a group of software developers as they navigate through coding challenges, office dynamics, and pursue their dreams.",
      duration: 110,
      ratings: 4.7,
      totalRating: 2000,
      releaseYear: 2023,
      releaseDate: "2023-09-15",
      genres: ["Comedy", "Drama"],
      directors: ["Jane Smith"],
      coverImage: "https://example.com/debugging-dreams-cover.jpg",
      actors: ["Alex Coder", "Lily Developer", "Max Bugcatcher"],
     price: 8.99
    },
    {
      name: "Pulp Fiction",
      description: "A nonlinear crime film intertwining various interconnected stories in Los Angeles.",
      duration: 154,
      ratings: 4.7,
      totalRating: 1800,
      releaseYear: 1994,
      releaseDate: "1994-10-14",
      genres: ["Crime", "Drama"],
      directors: ["Quentin Tarantino"],
      coverImage: "https://example.com/pulp-fiction-cover.jpg",
      actors: ["John Travolta", "Samuel L. Jackson", "Uma Thurman"],
      price: 8.99
    },
    {
      name: "Inception",
      description: "A mind-bending heist movie that explores the realm of dreams and subconsciousness.",
      duration: 148,
      ratings: 4.8,
      totalRating: 2500,
      releaseYear: 2010,
      releaseDate: "2010-07-16",
      genres: ["Action", "Sci-Fi", "Thriller"],
      directors: ["Christopher Nolan"],
      coverImage: "https://example.com/inception-cover.jpg",
      actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
      price: 12.99
    },
    {
      name: "The Matrix",
      description: "A mind-bending sci-fi thriller set in a simulated reality known as the Matrix.",
      duration: 136,
      ratings: 4.5,
      totalRating: 1000,
      releaseYear: 1999,
      releaseDate: "1999-03-31",
      genres: ["Action", "Sci-Fi"],
      directors: ["Lana Wachowski", "Lilly Wachowski"],
      coverImage: "https://example.com/the-matrix-cover.jpg",
      actors: ["Keanu Reeves", "Carrie-Anne Moss", "Laurence Fishburne"],
      price: 9.99
    },
    {
      name: "War Room",
      description: "A powerful story about the power of prayer and faith in the midst of personal struggles.",
      duration: 120,
      ratings: 4.6,
      totalRating: 900,
      releaseYear: 2015,
      releaseDate: "2015-08-28T00:00:00.000Z",
      createdAt: "2023-07-06T14:00:15.945Z",
      genres: ["Drama", "Faith"],
      directors: ["Alex Kendrick"],
      coverImage: "https://example.com/war-room-cover.jpg",
      actors: ["Priscilla Shirer", "T.C. Stallings", "Karen Abercrombie"],
      price: 7.99
    },
    {
      name: "The Passion of the Christ",
      description: "A powerful portrayal of the final hours of Jesus Christ's life, emphasizing his crucifixion and resurrection.",
      duration: 126,
      ratings: 4.8,
      totalRating: 3200,
      releaseYear: 2004,
      releaseDate: "2004-02-25T00:00:00.000Z",
      createdAt: "2023-07-06T14:00:15.945Z",
      genres: ["Drama", "Faith"],
      directors: ["Mel Gibson"],
      coverImage: "https://example.com/passion-of-the-christ-cover.jpg",
      actors: ["Jim Caviezel", "Maia Morgenstern", "Monica Bellucci"],
      price: 9.99
    },
    {
      name: "The Code",
      description: "A thrilling movie that explores the world of hackers, cybersecurity, and the challenges faced by software developers.",
      duration: 120,
      ratings: 4.5,
      totalRating: 1500,
      releaseYear: 2022,
      releaseDate: "2022-06-10T00:00:00.000Z",
      createdAt: "2023-07-06T14:00:15.945Z",
      genres: ["Thriller", "Drama"],
      directors: ["John Doe"],
      coverImage: "https://example.com/the-code-cover.jpg",
      actors: ["Emma Developer", "Tom Hacker", "Michael Coder"],
      price: 10.99
    },
    {
      name: "The Shawshank Redemption",
      description: "Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.",
      duration: 142,
      ratings: 9.3,
      totalRating: 2493185,
      releaseYear: 1994,
      releaseDate: "1994-09-23",
      genres: ["Drama"],
      directors: ["Frank Darabont"],
      coverImage: "https://example.com/shawshank-redemption.jpg",
      actors: ["Tim Robbins", "Morgan Freeman"],
      price: 9.99
    },
    {
      name: "The Godfather",
      description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      duration: 175,
      ratings: 9.2,
      totalRating: 1729608,
      releaseYear: 1972,
      releaseDate: "1972-03-24",
      genres: ["Crime", "Drama"],
      directors: ["Francis Ford Coppola"],
      coverImage: "https://example.com/the-godfather.jpg",
      actors: ["Marlon Brando", "Al Pacino"],
      price: 7.99
    },
    {
      name: "Schindler's List",
      description: "In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
      duration: 195,
      ratings: 8.9,
      totalRating: 1221593,
      releaseYear: 1993,
      releaseDate: "1993-12-15",
      genres: ["Biography", "Drama", "History"],
      directors: ["Steven Spielberg"],
      coverImage: "https://example.com/schindlers-list.jpg",
      actors: ["Liam Neeson", "Ralph Fiennes"],
      price: 8.99
    },
    {
      name: "Fight Club",
      description: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
      duration: 139,
      ratings: 8.8,
      totalRating: 1907970,
      releaseYear: 1999,
      releaseDate: "1999-10-15",
      genres: ["Drama"],
      directors: ["David Fincher"],
      coverImage: "https://example.com/fight-club.jpg",
      actors: ["Brad Pitt", "Edward Norton"],
      price: 7.99
    },
    {
      name: "The Lord of the Rings: The Fellowship of the Ring",
      description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
      duration: 178,
      ratings: 8.8,
      totalRating: 1693593,
      releaseYear: 2001,
      releaseDate: "2001-12-19",
      genres: ["Action", "Adventure", "Drama"],
      directors: ["Peter Jackson"],
      coverImage: "https://example.com/lotr-fellowship-of-the-ring.jpg",
      actors: ["Elijah Wood", "Ian McKellen"],
      price: 9.99
    },
    {
      name: "The Dark Knight",
      description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      duration: 152,
      ratings: 9.0,
      totalRating: 2373709,
      releaseYear: 2008,
      releaseDate: "2008-07-18",
      genres: ["Action", "Crime", "Drama"],
      directors: ["Christopher Nolan"],
      coverImage: "https://example.com/the-dark-knight.jpg",
      actors: ["Christian Bale", "Heath Ledger"],
      price: 7.99
    },
    {
      name: "The Departed",
      description: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
      duration: 151,
      ratings: 8.5,
      totalRating: 1234567,
      releaseYear: 2006,
      releaseDate: "2006-10-06",
      genres: ["Crime", "Drama", "Thriller"],
      directors: ["Martin Scorsese"],
      coverImage: "https://example.com/the-departed.jpg",
      actors: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"],
      price: 6.99
    }
  ]
  